---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playlist-recommend-server-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: "project2-pv-yl685"
